### PR TITLE
Update ukraine.py

### PR DESCRIPTION
**Pull request by ArcLightSlavik**
refs #

Ukraine had a lot of changes with holidays, most of which are described here: https://en.wikipedia.org/wiki/Public_holidays_in_Ukraine

list:

- Victory day from May 9 to May 8 with a name change
- Statehood day added
- Defenders day moved
- Old orthodox day removed

For information, read and make sure you're okay with the [Contributing guidelines](https://workalendar.github.io/workalendar/contributing.html#adding-new-calendars).

- [ ] Tests with a significant number of years to be tested for your calendar.
- [ ] Docstrings for the Calendar class and specific methods.
- [ ] Use the ``workalendar.registry_tools.iso_register`` decorator to register your new calendar using ISO codes (optional).
- [ ] Calendar country / label added to the README.md file.
- [ ] Changelog amended with a mention like: "Added ``<country>`` by ``@pseudo`` (#)". **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

- [ ] Tests with a significant number of years to be tested for your calendar.
- [ ] Changelog amended with a mention describing your changes. **Note** *Please do NOT change the version number here. It's the project maintainers' duty.*

### CODE REVIEW

**Comment by ArcLightSlavik** [comment]
@jaraco

**Comment by jaraco** [comment]
Should these changes include tests to capture the new expectations?

**Comment by jaraco** [comment]
I see some failed tests seemingly due to the changes:

```
FAILED calendra/tests/test_europe.py::UkraineTest::test_ical_export - AttributeError: 'int' object has no attribute 'year'
FAILED calendra/tests/test_europe.py::UkraineTest::test_january_1st - AttributeError: 'int' object has no attribute 'year'
FAILED calendra/tests/test_europe.py::UkraineTest::test_may_1st_label - AttributeError: 'int' object has no attribute 'year'
FAILED calendra/tests/test_europe.py::UkraineTest::test_year_2015 - AttributeError: 'int' object has no attribute 'year'
FAILED calendra/tests/test_europe.py::UkraineTest::test_year_2016 - AttributeError: 'int' object has no attribute 'year'
FAILED calendra/tests/test_europe.py::UkraineTest::test_year_2017 - AttributeError: 'int' object has no attribute 'year'
FAILED calendra/tests/test_europe.py::UkraineTest::test_year_2018 - AttributeError: 'int' object has no attribute 'year'
```

Consider running `tox` in the checkout to validate the behavior.

**Comment by ArcLightSlavik** [comment]
should be fine now, fixed and added tests for 23/24 @jaraco 

Screenshot 2024-10-07 at 03 23 47

**Comment by jaraco** [comment]
Sorry for the delay in reviewing. I've been slammed since starting my new job. Let's get this out.

**Pull request merged**
